category_controllers:
    resource:
        path: ../src/Category/Application/
        namespace: App\Category\Application
    type: attribute
    prefix: /api/v1
    trailing_slash_on_root: false

person_controllers:
    resource:
        path: ../src/Person/Application/
        namespace: App\Person\Application
    type: attribute
    prefix: /api/v1
    trailing_slash_on_root: false

expense_controllers:
    resource:
        path: ../src/Expense/Application/
        namespace: App\Expense\Application
    type: attribute
    prefix: /api/v1
    trailing_slash_on_root: false
